### ISSUE TITLE
登录页面崩溃

### ISSUE THREAD

**Issue by zhj0128** [ShowMeThe/MaterialWanAndroid#1]
尝试运行点击登录和注册页面，发现崩溃了

2020-04-01 16:36:49.253 10462-10462/com.ken.wanandroid E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ken.wanandroid, PID: 10462
    java.lang.RuntimeException: Failed to call observer method
        at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:226)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:194)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:185)
        at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:37)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:300)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:339)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131)
        at androidx.fragment.app.Fragment.performStart(Fragment.java:2735)
        at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:365)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1194)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:442)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.showmethe.skinlib.SkinManager.patchView(SkinManager.kt:352)
        at com.showmethe.skinlib.SkinManager$Companion.patchView(SkinManager.kt:117)
        at com.showmethe.skinlib.SkinExtKt.skin(SkinExt.kt:21)
        at com.show.wanandroid.databinding.FragmentLoginBindingImpl.executeBindings(FragmentLoginBindingImpl.java:373)
        at androidx.databinding.ViewDataBinding.executeBindingsInternal(ViewDataBinding.java:472)
        at androidx.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:444)
        at androidx.databinding.ViewDataBinding$OnStartListener.onStart(ViewDataBinding.java:1685)
        at java.lang.reflect.Method.invoke(Native Method)
        at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:216)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:194) 
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:185) 
        at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:37) 
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361) 
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:300) 
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:339) 
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145) 
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131) 
        at androidx.fragment.app.Fragment.performStart(Fragment.java:2735) 
        at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:365) 
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1194) 
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356) 
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434) 
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:442) 
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169) 
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992) 
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947) 
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849) 
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413) 
        at android.os.Handler.handleCallback(Handler.java:907) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7625) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) 
2020-04-01 16:36:49.258 10462-10462/com.ken.wanandroid E/Crash: Failed to call observer method

**Comment by ShowMeThe** [comment]
@zhj0128 拿一下最新代码 这个项目昨天还在修改中

**Comment by zhj0128** [comment]
我clone 下来的，这个bug没变，在登录页面（从侧滑栏进入登录页面，然后点击登录或者注册按钮），额，感谢无私分享，只是反馈下，哈哈
   Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.showmethe.skinlib.SkinManager.patchView(SkinManager.kt:352)
        at com.showmethe.skinlib.SkinManager$Companion.patchView(SkinManager.kt:117)
        at com.showmethe.skinlib.SkinExtKt.skin(SkinExt.kt:21)
        at com.show.wanandroid.databinding.FragmentLoginBindingImpl.executeBindings(FragmentLoginBindingImpl.java:373)

**Comment by ShowMeThe** [comment]
我想起来什么问题了 ，是那个光标的设置问题，因为我调用了Android Q 新的API setTextCursorDrawable,低于Android Q的我改成反射了，你晚点再拉代码看看，或者在登录的地方去掉那个EditText 那里去掉 skin=“@{`cursor`}”这个
@zhj0128
